# .mockery.yaml
with-expecter: true
packages:
  github.com/irvanmhndra/pos-core-api/internal/repository:
    interfaces:
      UserRepository:
      CompanyRepository:
      BranchRepository:
      UserSessionRepository:
      RoleRepository:
      PermissionRepository:
      RolePermissionRepository:
      UserBranchRepository:
      CustomerRepository:
      ProductCategoryRepository:
      ProductRepository:
      ProductVariantRepository:
      OrderRepository:
      OrderItemRepository:
      PaymentRepository:
      CompanySettingsRepository:
      PromotionRepository:
      ReportRepository:
    config:
      dir: internal/repository/mocks
      outpkg: mocks

  github.com/irvanmhndra/pos-core-api/internal/client/payment:
    interfaces:
      Gateway:
    config:
      dir: internal/client/mocks
      outpkg: mocks

  github.com/irvanmhndra/pos-core-api/internal/event/publisher:
    interfaces:
      EventPublisher:
    config:
      dir: internal/event/mocks
      outpkg: mocks